version: '3.5'

networks:
  default:
    external:
      name: dt-api

services:
  dt-api:
    image: justnbxgxdocker/digital-timbersaw-api:latest
    container_name: hci-api
    ports:
      - 8080:80
    volumes:
      - /data/prod/:/data/prod/
    environment:
      SPRING_PROFILES_ACTIVE: master
