spring:
  profiles:
    active: master
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB
  datasource:
    url: jdbc:mysql://localhost:3306/digital_timbersaw?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: true
  jackson:
    default-property-inclusion: non_absent

  mail:
    host: smtp.gmail.com
    port: 587
    username: digital.timbersaw.llc@gmail.com
    password: nmxebudufvynnvao
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

mail:
  from: digital.timbersaw.llc@gmail.com
  to: digital.timbersaw.llc@gmail.com
  subject: ??????????

server:
  servlet:
    context-path: /api
  port: 81

upload:
  file:
    base-path: /data/prod/